export const SHOW_SNACK_BAR = "SHOW_SNACK_BAR";
export const CLOSE_SNACK_BAR = "CLOSE_SNACK_BAR";

export const ACTION_GET_CAR_TYPE = {
  ACTION_GET_CAR_TYPE_REQUEST: "ACTION_GET_CAR_TYPE_REQUEST",
  ACTION_GET_CAR_TYPE_FAILED: "ACTION_GET_CAR_TYPE_FAILED",
  ACTION_GET_CAR_TYPE_SUCCESS: "ACTION_GET_CAR_TYPE_SUCCESS",
};
export const ACTION_GET_INSURE_COMPANIES = {
  ACTION_GET_INSURE_COMPANIES_REQUEST: "ACTION_GET_INSURE_COMPANIES_REQUEST",
  ACTION_GET_INSURE_COMPANIES_FAILED: "ACTION_GET_INSURE_COMPANIES_FAILED",
  ACTION_GET_INSURE_COMPANIES_SUCCESS: "ACTION_GET_INSURE_COMPANIES_SUCCESS",
};
export const ACTION_GET_THIRD_DISCOUNT = {
  ACTION_GET_THIRD_DISCOUNT_REQUEST: "ACTION_GET_THIRD_DISCOUNT_REQUEST",
  ACTION_GET_THIRD_DISCOUNT_FAILED: "ACTION_GET_THIRD_DISCOUNT_FAILED",
  ACTION_GET_THIRD_DISCOUNT_SUCCESS: "ACTION_GET_THIRD_DISCOUNT_SUCCESS",
};
export const ACTION_GET_DRIVER_DISCOUNT = {
  ACTION_GET_DRIVER_DISCOUNT_REQUEST: "ACTION_GET_DRIVER_DISCOUNT_aREQUEST",
  ACTION_GET_DRIVER_DISCOUNT_FAILED: "ACTION_GET_DRIVER_DISCOUNT_FAILED",
  ACTION_GET_DRIVER_DISCOUNT_SUCCESS: "ACTION_GET_DRIVER_DISCOUNT_SUCCESS",
};
export const ACTION_SHOW_MODAL = "ACTION_SHOW_MODAL";
export const ACTION_CLOSE_MODAL = "ACTION_CLOSE_MODAL";
export const ACTION_CHANGE_WIZARD = "ACTION_CHANGE_WIZARD";
export const ACTION_CHANGE_PROFILE = "ACTION_CHANGE_PROFILE";
export const ACTION_SELECT_CAR = "ACTION_SELECT_CAR";
export const ACTION_SELECT_OLD_INSURE_COMPANY = "ACTION_SELECT_OLD_INSURE_COMPANY";
export const ACTION_SELECT_DISCOUNT = "ACTION_SELECT_DISCOUNT";
